server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          github:
            client-id: 8181341fb0665cbf85ab
            client-secret: 1c0cb3836c25f7079b3e268357ac47cd4f68ff75
          facebook:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          okta:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          aad:
            client-id: 5b5f0311-76b8-4d94-aacf-89e44f1c6630
            client-secret: kAA8f1UL=5d@Z-AyV:gj46MCboEhu42s
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid,profile
            client-name: AAD
        provider:
          okta:
            authorization-uri: https://your-subdomain.oktapreview.com/oauth2/v1/authorize
            token-uri: https://your-subdomain.oktapreview.com/oauth2/v1/token
            user-info-uri: https://your-subdomain.oktapreview.com/oauth2/v1/userinfo
            jwk-set-uri: https://your-subdomain.oktapreview.com/oauth2/v1/keys
          aad:
            issuer-uri: https://login.partner.microsoftonline.cn/9ba5de4c-51b3-4cd4-a2d5-b3e09ecfc26e/v2.0
#            authorization-uri: https://login.chinacloudapi.cn/9ba5de4c-51b3-4cd4-a2d5-b3e09ecfc26e/oauth2/v2.0/authorize
#            token-uri: https://login.chinacloudapi.cn/9ba5de4c-51b3-4cd4-a2d5-b3e09ecfc26e/oauth2/v2.0/token
#            user-info-uri: https://microsoftgraph.chinacloudapi.cn/oidc/userinfo
#            userNameAttribute: sub
#            jwk-set-uri: https://login.chinacloudapi.cn/9ba5de4c-51b3-4cd4-a2d5-b3e09ecfc26e/discovery/v2.0/keys
